---
- name: Add Helm dependencies for repo setup
  ansible.builtin.apt:
    name:
      - apt-transport-https

- name: Add Helm GPG keys
  ansible.builtin.apt_key:
    url: https://baltocdn.com/helm/signing.asc
    state: present

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://baltocdn.com/helm/stable/debian/ all main
    state: present

- name: Install Helm
  ansible.builtin.apt:
    name: helm
    state: present
    update_cache: true

- name: Install Helm Repo For Rook
  kubernetes.core.helm_repository:
    name: rook-release
    repo_url: https://charts.rook.io/release

- name: Deploy Rook Chart
  kubernetes.core.helm:
    name: rook-ceph
    chart_ref: rook-release/rook-ceph
    namespace: rook-ceph
    create_namespace: true
    state: present
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
